openapi: 3.0.3
info:
  title: Pillar 2 API
  description: An API for managing and retrieving data in accordance with Pillar 2 tax rules.
paths:
  /uk-tax-return:
    post:
      summary: SubmitUKTR
      description: |
        Submits a UK Tax Return for a specified accounting period.
        ### Field Reference
        <p>This table contains a list of the fields which make up the SubmitUKTR and AmendUKTR API requests.</p>
        <table>
        <thead>
        <tr>
        <th>Name</th>
        <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>accountingPeriodFrom</td>
        <td>Start date of accounting period supplied by the group at registration.</td>
        </tr>
        <tr>
        <td>accountingPeriodTo</td>
        <td>End date of accounting period supplied by the group at registration.</td>
        </tr>
        <tr>
        <td>obligationMTT</td>
        <td>Flag indicating if the group will pay Multinational Top-up Tax (<strong>MTT</strong>).</td>
        </tr>
        <tr>
        <td>electionUKGAAP</td>
        <td>Only a domestic group can have a UK GAAP election. It allows a domestic group to use UK GAAP when calculating the amount of Domestic Top-up Tax (<strong>DTT</strong>) due.</td>
        </tr>
        <tr>
        <td>electionDTTSingleMember</td>
        <td>Single member of the group who will submit returns and make payments on behalf of the entire group (only for DTT payments).</td>
        </tr>
        <tr>
        <td>electionUTPRSingleMember</td>
        <td>Single member of the group who will submit returns and make payments on behalf of the entire group (only for Under Taxed Profit Rule (<strong>UTPR</strong>) payments).</td>
        </tr>
        <tr>
        <td>numberSubGroupDTT</td>
        <td>Number of liable entities in the liable entities table where the DTT amount owed is greater than 0.</td>
        </tr>
        <tr>
        <td>numberSubGroupUTPR</td>
        <td>Number of liable entities in the liable entities table where the UTPR amount owed is greater than 0.</td>
        </tr>
        <tr>
        <td>totalLiability</td>
        <td>The overall total of tax due (incorporates DTT, Income Inclusion Rule (<strong>IIR</strong>) and UTPR).</td>
        </tr>
        <tr>
        <td>totalLiabilityDTT</td>
        <td>The overall total of tax due for entities with DTT liabilities.</td>
        </tr>
        <tr>
        <td>totalLiabilityIIR</td>
        <td>The overall total of tax due for entities with IIR liabilities.</td>
        </tr>
        <tr>
        <td>totalLiabilityUTPR</td>
        <td>The overall total of tax due for entities with UTPR liabilities.</td>
        </tr>
        <tr>
        <td>ukChargeableEntityName</td>
        <td>Name of the Entity liable for tax payments.</td>
        </tr>
        <tr>
        <td>idType</td>
        <td>Unique identifier type for the entity, which is either the Company Registration Number (<strong>CRN</strong>) or Unique Taxpayer Reference (<strong>UTR</strong>) for corporation tax.</td>
        </tr>
        <tr>
        <td>idValue</td>
        <td>Unique identifier for the entity, either a CRN or UTR depending on the <em>idType</em> entered.</td>
        </tr>
        <tr>
        <td>amountOwedDTT</td>
        <td>Amount of DTT owed by the entity.</td>
        </tr>
        <tr>
        <td>amountOwedIIR</td>
        <td>Amount of IIR owed by the entity.</td>
        </tr>
        <tr>
        <td>amountOwedUTPR</td>
        <td>Amount of UTPR owed by the entity.</td>
        </tr>
        <tr>
        <td>returnType</td>
        <td>Only supplied with Nil Return.</td>
        </tr>
        </tbody>
        </table>
        
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitUKTR or AmendUKTR API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar 2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation Already Fulfilled</td>
        <td>A UKTR for the specified period has already been submitted. If you are trying to amend a UKTR, please check you are sending the <em>amendUKTR</em> API request.</td>
        </tr>
        <tr>
        <td>063 - Business Partner does not have an Active Pillar 2 Subscription</td>
        <td>The Pillar 2 ID (SAP Number) in the request header is not listed as active by HMRC for this regime. Please contact the central support team.</td>
        </tr>
        <tr>
        <td>093 - Invalid Return</td>
        <td>There is an error with the tax return you’ve submitted in the request. Please complete the following checks. 
        <li>Review the <em>accountingPeriodFrom</em> and <em>accountingPeriodTo</em> fields to ensure the dates are valid. If you need to check or amend the accounting period pattern, you can do this on the Pillar 2 site under “Personal Details”.</li>
        <li>If the <em>obligationMTT field</em> is set to <em>false</em>, check the value entered for both <em>amountOwedIIR</em> and <em>amountOwedUTPR</em> is 0.</li></td>
        </tr>
        <tr>
        <td>094 - Invalid DTT Election</td>
        <td>The DTT values in the request are invalid. Please complete the following checks, then submit the request again. If <em>electionDTTSingleMember</em> is true, the <em>numberSubGroupDTT</em> should be greater than 0. This number represents the number of liable entities that owe a DTT amount greater than 0. The total number of liable entities who owe DTT in the payload should be the same as the number in <em>numberSubGroupDTT</em>.</td>
        </tr>
        <tr>
        <td>095 - Invalid UTPR Election</td>
        <td>The UTPR values in the request are invalid. Please complete the following checks, then submit the request again. If <em>electionUTPRSingleMember</em> is true, the <em>numberSubGroupUTPR</em> should be greater than 0. This number represents the number of liable entities that owe a UTPR amount greater than 0. The total number of liable entities who owe UTPR in the payload should be the same as the number in <em>numberSubGroupUTPR</em>.</td>
        </tr>
        <tr>
        <td>096 - Invalid Total Liability</td>
        <td>The <em>totalLiability</em> value in the request does not match the combined values of <em>totalLiabilityDTT</em>, <em>totalLiabilityIIR</em> and <em>totalLiabilityUTPR</em>. Please check the sum of these fields matches the <em>totalLiability</em> value and submit the request again.</td>
        </tr>
        <tr>
        <td>097 - Invalid Total Liability IIR</td>
        <td>The <em>totalLiabilityIIR</em> value does not match the <em>amountIIR value</em> from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>098 - Invalid Total Liability DTT</td>
        <td>The <em>totalLiabilityDTT</em> value does not match the <em>amountDTT</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>099 - Invalid Total Liability UTPR</td>
        <td>The <em>totalLiabilityUTPR</em> value does not match the <em>amountUTPR</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        </tbody>
        </table>       
      security:
        - userRestricted: [write:pillar2]
    put:
      summary: AmendUKTR
      description: |
        Amends a UK tax return submitted for a specified accounting period.   
        ### Field Reference
        <p>AmendUKTR uses the same range of fields as SubmitUKTR, please use the Field Reference table in the SubmitUKTR section above.</p>
        ### Error Codes
        <p>AmendUKTR generates the same error codes as SubmitUKTR, please use the Error Codes table in the SubmitUKTR section above.</p>        
      security:
        - userRestricted: [write:pillar2]
  /below-threshold-notification:
    post:
      summary: SubmitBTN
      description: |
        Submits a Below-Threshold Notification for a specified accounting period when the group no longer meets the threshold for the Pillar 2 top-up tax.
        ### Field Reference
        <p>This table contains a list of the fields which make up the SubmitBTN request.</p>
        <table>
        <thead>
        <tr>
        <th>Name</th>
        <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>accountingPeriodFrom</td>
        <td>Start date of accounting period supplied by the group at registration.</td>
        </tr>
        <tr>
        <td>accountingPeriodTo</td>
        <td>End date of accounting period supplied by the group at registration.</td>
        </tr>
        <tr>
        <td>processingDate</td>
        <td>Confirmation timestamp for successful response.</td>
        </tr>
        </tbody>
        </table>
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitBTN API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation already fulfilled</td>
        <td>A BTN for the specified period has already been submitted.</td>
        </tr>
        <tr>
        <td>063 - Business Partner does not have an Active Pillar 2 Subscription</td>
        <td>The Pillar 2 ID (SAP Number) in the request header is not listed as active by HMRC for this regime. Please contact the central support team.</td>
        </tr>
        </tbody>
        </table>
      security:
        - userRestricted: [write:pillar2]
  /obligations-and-submissions:
    get:
      summary: Retrieve Obligations and Submissions
      description: |
        Retrieves the Obligations and Submissions for an accounting period.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a Obligations and Submissions API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar2 ID (SAP Number) is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID (SAP Number) they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please check if there is currently an open enquiry on your tax account.</td>
        </tr>
        <tr>
        <td>025 - No associated data found</td>
        <td>No associated data found for this Pillar 2 ID.</td>
        </tr>
        <tr>
        </tbody>
        </table>
      security:
        - userRestricted: [write:pillar2]
  /setup/organisation:
    post:
      summary: Create Test Organisation
      description: |
        Creates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    get:
      summary: Get Test Organisation
      description: |
        Gets a test organisation associated with your authed organisation.
      security:
        - userRestricted: [read:pillar2]
    put:
      summary: Update Test Organisation
      description: |
        Updates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    delete:
      summary: Delete Test Organisation
      description: |
        Deletes a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
   
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        Please see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:pillar2: Read data related to Pillar2 subscription
            write:pillar2: Write data related to Pillar2 subscription
