---
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: BigDecimal
  specAsParameter:
    - type: number
      format: double
      minimum: 0
      maximum: 9999999999999.99