---
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: BigDecimal
  specAsParameter:
    - type: number
      format: double
      minimum: 0
      maximum: 9999999999999.99
- type: java\.time\.LocalDate
  specAsParameter:
    - type: string
      format: date
- type: cats\.data\.NonEmptyList\[uk\.gov\.hmrc\.pillar2submissionapi\.models\.uktrsubmissions\.LiableEntity\]
  specAsParameter:
    - type: array
      minItems: 1
      items:
        $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.uktrsubmissions.LiableEntity"