---
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: BigDecimal
  specAsParameter:
    - type: number
      format: double
      minimum: 0
      maximum: 9999999999999.99
- type: java\.time\.LocalDate
  propertyName: accountingPeriodFrom
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      format: date
  schema:
    type: string
    format: date
- type: java\.time\.LocalDate
  propertyName: accountingPeriodTo
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      format: date
  schema:
    type: string
    format: date
- type: java\.time\.LocalDate
  propertyName: filedDateGIR
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      format: date
  schema:
    type: string
    format: date
- type: String
  propertyName: countryGIR
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 2
  schema:
    type: string
    minLength: 1
    maxLength: 2
- type: String
  propertyName: reportingEntityName
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 200
  schema:
    type: string
    minLength: 1
    maxLength: 200
- type: String
  propertyName: TIN
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 200
  schema:
    type: string
    minLength: 1
    maxLength: 200
- type: String
  propertyName: issuingCountryTIN
  in: uk.gov.hmrc.pillar2submissionapi.models.overseasreturnnotification.ORNSubmission
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 2
  schema:
    type: string
    minLength: 1
    maxLength: 2