openapi: 3.0.3
info:
  title: Pillar 2 API
  description: An API for managing and retrieving data in accordance with Pillar 2 tax rules.
paths:
  /uk-tax-return:
    post:
      summary: SubmitUKTR
      description: |
        Submits a UK Tax Return for a specified accounting period.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitUKTR or AmendUKTR API request is not processed successfully. Error codes still in development are marked as "awaiting clarification".</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar 2 ID required</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please send the request again.</td>
        </tr>
        <tr>
        <td>007 - Business Partner does not have an Active Subscription</td>
        <td>The request Pillar 2 ID is not listed as active by HMRC. Please contact the central support team.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation Already Fulfilled</td>
        <td>A UKTR for the specified period has already been submitted. If you are trying to amend a UKTR, please check you are sending the <em>amendUKTR</em> API request.</td>
        </tr>
        <tr>
        <td>093 - Invalid Return</td>
        <td>There is an error with the tax return you’ve submitted in the request. Awaiting clarification.</td>
        </tr>
        <tr>
        <td>094 - Invalid DTT Election</td>
        <td>The DTT values in the request are invalid. Awaiting clarification.</td>
        </tr>
        <tr>
        <td>095 - Invalid UTPR Election</td>
        <td>The UTPR values in the request are invalid. Awaiting clarification.</td>
        </tr>
        <tr>
        <td>096 - Invalid Total Liability</td>
        <td>The <em>totalLiability</em> value in the request does not match the combined values of <em>totalLiabilityDTT</em>, <em>totalLiabilityIIR</em> and <em>totalLiabilityUTPR</em>. Please check the sum of these fields matches the <em>totalLiability</em> value and submit the request again.</td>
        </tr>
        <tr>
        <td>097 - Invalid Total Liability IIR</td>
        <td>The <em>totalLiabilityIIR</em> value does not match the <em>amountIIR value</em> from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>098 - Invalid Total Liability DTT</td>
        <td>The <em>totalLiabilityDTT</em> value does not match the <em>amountDTT</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        <tr>
        <td>099 - Invalid Total Liability UTPR</td>
        <td>The <em>totalLiabilityUTPR</em> value does not match the <em>amountUTPR</em> value from the <em>liableEntities</em> array. Please check the value of these fields matches and submit the request again.</td>
        </tr>
        </tbody>
        </table>       
      security:
        - userRestricted: [write:pillar2]
    put:
      summary: AmendUKTR
      description: |
        Amends a UK tax return submitted for a specified accounting period.   
        
        ### Error Codes
        <p>AmendUKTR generates the same error codes as Submit UKTR, please use the Error Codes table in the SubmitUKTR section above.</p>        
      security:
        - userRestricted: [write:pillar2]
  /below-threshold-notification:
    post:
      summary: SubmitBTN
      description: |
        Submits a Below-Threshold Notification for a specified accounting period when the group no longer meets the threshold for the Pillar 2 top-up tax.
        ### Error Codes
        <p>This table contains a list of 422 error codes returned when a SubmitBTN API request is not processed successfully.</p>
        <table>
        <thead>
        <tr>
        <th>Error Message</th>
        <th>Next Steps</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>002 - Pillar2 ID is missing or invalid</td>
        <td>Please provide the request header for your client, to check it contains the Pillar 2 ID they were assigned at registration.</td>
        </tr>
        <tr>
        <td>003 - Request could not be processed</td>
        <td>The message could not be processed due to locking. Please send the request again.</td>
        </tr>
        <tr>
        <td>007 - Business Partner does not have an Active Pillar 2 registration</td>
        <td>The request Pillar 2 ID is not listed as active by HMRC. Please contact the central support team.</td>
        </tr>
        <tr>
        <td>044 - Tax Obligation already fulfilled</td>
        <td>A BTN for the specified period has already been  submitted.</td>
        </tr>
        </tbody>
        </table>
      security:
        - userRestricted: [write:pillar2]
  /setup/organisation:
    post:
      summary: Create Test Organisation
      description: |
        Creates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    get:
      summary: Get Test Organisation
      description: |
        Gets a test organisation associated with your authed organisation.
      security:
        - userRestricted: [read:pillar2]
    put:
      summary: Update Test Organisation
      description: |
        Updates a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
    delete:
      summary: Delete Test Organisation
      description: |
        Deletes a test organisation associated with your authed organisation.
      security:
        - userRestricted: [write:pillar2]
   
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        Please see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:pillar2: Read data related to Pillar2 subscription
            write:pillar2: Write data related to Pillar2 subscription
