---
- type: java\.time\.ZonedDateTime
  specAsParameter:
    - type: string
      format: date-time
- type: uk\.gov\.hmrc\.pillar2submissionapi\.models\.Monetary
  specAsParameter:
    - type: number
      format: double
      minimum: 0
      maximum: 9999999999999.99
      multipleOf: 0.01
- type: java\.time\.LocalDate
  specAsParameter:
    - type: string
      format: date
- type: uk\.gov\.hmrc\.pillar2submissionapi\.models\.uktrsubmissions\.LiableEntities
  specAsParameter:
    - type: array
      minItems: 1
      items:
        $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.uktrsubmissions.LiableEntity"
- type: uk\.gov\.hmrc\.pillar2submissionapi\.models\.uktrsubmissions\.IdType
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 4
- type: uk\.gov\.hmrc\.pillar2submissionapi\.models\.uktrsubmissions\.IdValue
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 15
- type: uk\.gov\.hmrc\.pillar2submissionapi\.models\.uktrsubmissions\.EntityName
  specAsParameter:
    - type: string
      minLength: 1
      maxLength: 160