openapi: 3.0.3
info:
  version: 0.60.0
  title: Pillar 2
  description: An API for managing and retrieving Pillar 2 data
tags: []
paths:
  /organisations/pillar-two/uk-tax-return:
    post:
      security:
      - userRestricted:
        - write:pillar2
      tags:
      - submission
      operationId: submitUKTR
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: "#/components/schemas/UKTRSubmissionData"
              - $ref: "#/components/schemas/UKTRSubmissionNilReturn"
      summary: Submit a Pillar2 UKTR
      responses:
        "201":
          description: UKTR Submission Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responses.UKTRSubmitSuccessResponse"
        "422":
          description: Business Validation Failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "400":
          description: Invalid Submission
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
    put:
      security:
      - userRestricted:
        - write:pillar2
      tags:
      - submission
      operationId: amendUKTR
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: "#/components/schemas/UKTRSubmissionData"
              - $ref: "#/components/schemas/UKTRSubmissionNilReturn"
      summary: Amend a Pillar2 UKTR
      responses:
        "200":
          description: UKTR Submission Amended
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responses.UKTRSubmitSuccessResponse"
        "422":
          description: Business Validation Failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "400":
          description: Invalid Submission
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
  /organisations/pillar-two/below-threshold-notification:
    post:
      security:
      - userRestricted:
        - write:pillar2
      tags:
      - submission
      operationId: submitBTN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BTNSubmission"
      summary: Submit a Pillar2 BTN
      responses:
        "201":
          description: UKTR Submission Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitBTNSuccessResponse"
        "422":
          description: Business Validation Failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "400":
          description: Invalid Submission
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse"
components:
  schemas:
    BTNSubmission:
      properties:
        accountingPeriodFrom:
          type: string
          format: date
        accountingPeriodTo:
          type: string
          format: date
      required:
      - accountingPeriodFrom
      - accountingPeriodTo
    SubmitBTNSuccessResponse:
      properties:
        processingDate:
          type: string
        formBundleNumber:
          type: string
        chargeReference:
          type: string
          nullable: true
      required:
      - processingDate
      - formBundleNumber
    UKTRSubmissionData:
      properties:
        electionUKGAAP:
          type: boolean
        accountingPeriodFrom:
          type: string
          format: date
        liabilities:
          $ref: "#/components/schemas/LiabilityData"
        accountingPeriodTo:
          type: string
          format: date
        obligationMTT:
          type: boolean
      required:
      - accountingPeriodFrom
      - accountingPeriodTo
      - obligationMTT
      - electionUKGAAP
      - liabilities
    LiableEntity:
      properties:
        idType:
          type: string
        idValue:
          type: string
        ukChargeableEntityName:
          type: string
        amountOwedUTPR:
          type: number
          format: double
        amountOwedIIR:
          type: number
          format: double
        amountOwedDTT:
          type: number
          format: double
      required:
      - ukChargeableEntityName
      - idType
      - idValue
      - amountOwedDTT
      - amountOwedIIR
      - amountOwedUTPR
    responses.UKTRSubmitSuccessResponse:
      properties:
        processingDate:
          type: string
          format: date-time
        formBundleNumber:
          type: string
        chargeReference:
          type: string
          nullable: true
      required:
      - processingDate
      - formBundleNumber
    LiabilityNilReturn:
      properties:
        returnType:
          type: string
          enum:
          - NIL_RETURN
      required:
      - returnType
    UKTRSubmissionNilReturn:
      properties:
        electionUKGAAP:
          type: boolean
        accountingPeriodFrom:
          type: string
          format: date
        liabilities:
          $ref: "#/components/schemas/LiabilityNilReturn"
        accountingPeriodTo:
          type: string
          format: date
        obligationMTT:
          type: boolean
      required:
      - accountingPeriodFrom
      - accountingPeriodTo
      - obligationMTT
      - electionUKGAAP
      - liabilities
    LiabilityData:
      properties:
        electionUTPRSingleMember:
          type: boolean
        electionDTTSingleMember:
          type: boolean
        numberSubGroupDTT:
          type: integer
          format: int32
        totalLiabilityDTT:
          type: number
          format: double
        totalLiabilityUTPR:
          type: number
          format: double
        numberSubGroupUTPR:
          type: integer
          format: int32
        liableEntities:
          type: array
          items:
            $ref: "#/components/schemas/LiableEntity"
        totalLiabilityIIR:
          type: number
          format: double
        totalLiability:
          type: number
          format: double
      required:
      - electionDTTSingleMember
      - electionUTPRSingleMember
      - numberSubGroupDTT
      - numberSubGroupUTPR
      - totalLiability
      - totalLiabilityDTT
      - totalLiabilityIIR
      - totalLiabilityUTPR
      - liableEntities
    uk.gov.hmrc.pillar2submissionapi.models.response.Pillar2ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:pillar2: Read data related to Pillar2 subscription
            write:pillar2: Write data related to Pillar2 subscription
